ktor:
    application:
        modules:
            - com.random.fact.ApplicationKt.module
    deployment:
        port: 8080

useless_facts_url: "https://uselessfacts.jsph.pl/random.json?language=en"